spring:
  profiles:
    active: prod
  data:
    rest:
      base-path: /api
  aop:
    proxy-target-class: false
    auto: false
server:
  tomcat:
    accesslog:
      directory: accesslog
      enabled: true
      prefix: access_log
      suffix: .log
      rotate: true
      file-date-format: .yyyy-MM-dd
      request-attributes-enabled: true
      pattern: combined
    basedir: personfilter_tomcat