spring:
  profiles:
    active: dev
server:
  tomcat:
    accesslog:
      directory: accesslog
      enabled: true
      prefix: access_log
      suffix: .log
      rotate: true
      file-date-format: .yyyy-MM-dd
      request-attributes-enabled: true
      pattern: combined
    basedir: personfilter_tomcat