server:
  port: 6200
  tomcat:
    uri-encoding: UTF-8
  user: http://120.24.5.178:7200
  max-http-header-size: 8192
spring:
  datasource:
    url: jdbc:mysql://47.94.248.38:3306/personfilter?characterEncoding=utf-8&useSSL=false
    username: root
    password: li197910
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 47.94.248.38
      port: 27017
      database: personfilter
  redis:
    host: 47.94.248.38
    timeout: 5000ms
    password: li197910
    port: 6666
  http:
    encoding:
      charset: utf-8
      enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  jackson:
      serialization:
        indent_output: true
  kafka:
    bootstrap-servers: 47.94.248.38:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: person
  mail:
    # 邮箱服务器地址，这里使用的是163.com的邮件服务器
      host: smtp.163.com
    # 在163.com注册的用户名，注意这里不需要@163.com后缀
      username: userscenter
    # 在163.com使用的授权码(关闭授权码时使用密码)，需要开启POP3/SMTP服务
      password: li1979101
# 以谁来发送邮件（发件人邮箱）
mail:
  fromMail:
    addr: userscenter@163.com