server:
  port: 6100
  tomcat:
    uri-encoding: UTF-8
  user: http://120.24.5.178:7200
  max-http-header-size: 8192
spring:
  datasource:
    username: root
    password: li197910
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/personfilter?characterEncoding=utf-8&useSSL=false
    hikari:
      max-lifetime: 0
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: personfilter
  http:
    encoding:
      charset: utf-8
      enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  jackson:
      serialization:
        indent_output: true
  mail:
      # 邮箱服务器地址，这里使用的是163.com的邮箱服务器
        host: smtp.163.com
      # 在163.com注册的用户名，注意这里不需要@163.com后缀
        username: userscenter@163.com
      # 在163.com使用的授权码(关闭授权码时使用密码)，需要开启POP3/SMTP服务
        password: li1979101
        port: 465
        default-encoding: UTF-8
debug: false
com:
  stalary:
    easydoc:
      contact: stalary@163.com
      description: 智能化招聘系统
      name: recruit
      open: true
      source: true
      path: com.stalary.personfilter